import streamlit as st
st.header("This site redirected to below link sorry for inconvenience")
st.markdown("https://rnadnadocs.streamlit.app/", unsafe_allow_html=True)
st.title("Overview :")
st.markdown("##### RNA&DNA is an advanced 3D production tracking and interactive web application designed to streamline project management and collaboration across various digital content creation (DCC) applications. Built with MongoDB and Python, this tool provides an intuitive and USD workflow, integrating seamlessly with leading industry software like MAYA, BLENDER, UNREAL, OMNIVERSE, SUBSTANCE PAINTER, HOUDINI, and NUKE.")
st.divider()
st.title("Key Features :")
st.markdown("#### User Management :")
st.divider()
st.markdown("#### Project & Team Management :")
st.divider()
st.markdown("#### USD Integration & Workflow Enhancements :")
st.markdown("#####	USD Environment Build & Tagging System :")
st.markdown("#####	USD to Unreal Material Conversion:")

st.divider()
st.markdown("#### Interactive User Status & Review Process :")
st.divider()
st.markdown("#### File Versioning & Permissions :")
st.divider()
st.markdown("### ------------Key feature Update soon  -------- :")
